name:                asmep
version:             0.1.0.0
github:              "figurantpp/asmep"
license:             BSD3
author:              "Renan Ribeiro"
maintainer:          "figurantpp@protonmail.com"
copyright:           "2023 Renan Ribeiro"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/figurantpp/asmep>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- array
- parsec
- mtl
- bytestring
- effectful

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  asmep-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asmep

tests:
  asmep-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asmep
